#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	START_BUTTON,
	SPIN_BUTTON,
	BET_VALUE_BUTTON,
	RESET_BUTTON,
	QUIT_BUTTON,
	RESTART_BUTTON,
	RESULT_IMAGE,
	SLOT_MACHINE,
	INFO_LABEL,
	BACKGROUND,
	DIALOG_BUTTON
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/